import MyFooter from "@/components/Footer";
import { getAllPublished,  } from "@/lib/notion";
import Head from "next/head";
import { Container,Text,Link,Card, Spacer } from "@nextui-org/react";
import MyNavBar from "@/components/myNavbar";
import ThemeSwitch from "@/components/ThemeSwitch";



 function BlogPage({posts}) {
    if(!posts) return <h1>No posts</h1>
    return (
      <div >
        <Head>
          <title>Prawegko|Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container>
      
        <main >
        <ThemeSwitch/>
      <MyNavBar/>
    
          <Spacer/>
         
          {posts.map((post, index) => (
            <Container key={index}css={{width:"60%"}}  >
            
            <Card>
                <Card.Header>
                <Link href={`/posts/${post.slug}`}>
                  {/* <a >{post.title}</a> */}
                  {post.title}
                  </Link>
                </Card.Header>
                <Card.Divider/>
                <Card.Body>
                <Text color="default">{post.date}</Text>
                <Text color="default">{post.description} ...</Text>
                </Card.Body>
                <Card.Footer>
                  <Link href={`/posts/${post.slug}`}>Read More..</Link>
                </Card.Footer>
            </Card>
            
           
            
                 
                  {/* <div>
                      {post.date}
                  </div>
              
              <p>
                {post.description}
              </p> */}
              <Spacer/>
            </Container>
          ))}
        </main>
        </Container>
        <Container>
        <footer >
        <MyFooter/>
        </footer>
        </Container>
      </div>
    )
  }

    export const getStaticProps = async()=>{
        const data = await getAllPublished()
            return{
                props:{
                    posts: data
                },
                revalidate: 60
            };
        

    }

    export default BlogPage;


 